services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev